name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v3

    - name: Set up compiler
      uses: egor-tensin/setup-gcc@v1
      with:
        gcc-version: '11' # Or your preferred version

    - name: Compile
      run: |
        gcc -o vtttosrt src/vtttosrt.c 
        # (Adjust the compilation command if needed)

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.os }}-build
        path: vtttosrt 